services:
  client:
    image: domniic/chat-nest-client:latest
    container_name: chat-nest-client
    ports:
      - "5173:5173"
    environment:
      # - VITE_SERVER_URI=http://localhost:3000
      - VITE_SERVER_URI=http://43.204.140.149:3000
    networks:
      - chat-nest

  server:
    image: domniic/chat-nest-server:latest
    container_name: chat-nest-server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      # - ORIGIN=http://localhost:5173
      - ORIGIN=http://43.204.140.149:5173
      # - MONGO_URI=mongodb://chat-nest-mongo:27017/
      - MONGO_URI=mongodb://chat-nest-mongo:27017/chat-nest
      - SECRET_KEY=e8c0*2$$cn0s^cnp1@wsxxp0
      # - SERVER_URI=http://localhost:3000
      - SERVER_URI=http://43.204.140.149:3000
      - NODE_ENV=development
    networks:
      - chat-nest
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: chat-nest-mongo
    # ports:
    #   - "27017:27017"
    networks:
      - chat-nest
    volumes:
      - mongo-data:/data/db

networks:
  chat-nest:
    driver: bridge

volumes:
  mongo-data:
    driver: local
